# Generated by Django 3.1.2 on 2020-10-22 01:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2020, 10, 22, 1, 37, 36, 747556, tzinfo=utc), max_length=45),
            preserve_default=False,
        ),
    ]
